apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: grafana-pg-kdb
  namespace: demo
spec:
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: DoNotTerminate
  version: "15.3"
